name: wheel

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build_wheel:
        runs-on: ubuntu-20.04
        container:
            image: ghcr.io/daizhirui/gp-sddf:22.04
            credentials:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}
        steps:
            - name: Checkout repository and submodules
              uses: actions/checkout@v3
              with:
                  submodules: recursive
            - name: git safe.directory
              run: git config --global --add safe.directory '*'
            - name: Install Python Packages
              run: pip3 install -r requirements.txt --user
            # - name: Build Wheel
            #   run: python3 setup.py bdist_wheel
            - name: Pip Install
              run: pip3 install . --user
